### ISSUE TITLE
Small upgrade for github.com/lestrrat-go/jwx (High)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#10]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=270578&groupId=333&sidebarIssueTask=14755&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: go.mod

==== TLDR ====
github.com/lestrrat-go/jwx is affected by 3 unique vulnerabilities. 1 is high and 2 are low.

==== How to fix ====
In order to fix all of these vulnerabilities, update github.com/lestrrat-go/jwx to 1.2.29.

**Comment by imdadmw** [comment]
Resolved
