### ISSUE TITLE
Minor upgrade for google.golang.org/grpc (High)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#11]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=105373&groupId=333&sidebarIssueTask=14756&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: go.mod

==== TLDR ====
google.golang.org/grpc is affected by 2 unique vulnerabilities. 1 is high and 1 is medium.

==== How to fix ====
In order to fix all of these vulnerabilities, update google.golang.org/grpc to 1.57.1.

**Comment by imdadmw** [comment]
Resolved
