### ISSUE TITLE
Minor upgrade for golang.org/x/net (High)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#12]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=21638&groupId=333&sidebarIssueTask=14757&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: go.mod

==== TLDR ====
golang.org/x/net is affected by 3 unique vulnerabilities. 1 is high and 2 are medium.

==== How to fix ====
In order to fix all of these vulnerabilities, update golang.org/x/net to 0.23.0.

**Comment by imdadmw** [comment]
Resolved
