### ISSUE TITLE
Minor upgrade for google.golang.org/protobuf (Medium)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#13]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=601166&groupId=333&sidebarIssueTask=14758&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: go.mod

==== TLDR ====
The protojson.Unmarshal function can enter an infinite loop when unmarshaling certain forms of invalid JSON. This condition can occur when unmarshaling into a message which contains a google.protobuf.Any value, or when the UnmarshalOptions.DiscardUnknown option is set.

==== How to fix ====
We recommend updating from 1.31.0 to 1.33.0.

**Comment by imdadmw** [comment]
Resolved
