### ISSUE TITLE
Minor upgrade for golang.org/x/crypto (Medium)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#14]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=166733&groupId=333&sidebarIssueTask=14759&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: go.mod

==== TLDR ====
The SSH transport protocol with certain OpenSSH extensions, found in OpenSSH before 9.6 and other products, allows remote attackers to bypass integrity checks such that some packets are omitted (from the extension negotiation message), and a client and server may consequently end up with a connection for which some security features have been downgraded or disabled, aka a Terrapin attack. This occurs because the SSH Binary Packet Protocol (BPP), implemented by these extensions, mishandles the handshake phase and mishandles use of sequence numbers. For example, there is an effective attack against SSH's use of ChaCha20-Poly1305 (and CBC with Encrypt-then-MAC).

==== How to fix ====
We recommend updating from 0.12.0 to 0.17.0.

**Comment by imdadmw** [comment]
Resolved
