### ISSUE TITLE
Secret leaked in docker-compose-local.yml (High)

### ISSUE THREAD

**Issue by mijho** [mirrorweb/.github#9]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=21646&groupId=333&sidebarIssueTask=14754&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- cerberus: dockerdata/env

==== TLDR ====
We detected secret *****N1CB in the git history of the repository. The secret was found in dockerdata/env.
View commit: https://github.com/mirrorweb/cerberus/blob/2aa84961395c6a63d5d6ef6a754a1cfdda123c48/dockerdata/env#L39

==== How to fix ====
If this API key is harmless, you can ignore this issue. If not, we would advise to move the secret out of the git repository by either injecting it via the environment or even better, by using a tool such as AWS Secrets Manager to inject the secrets at run-time. After that, it should be possible to invalidate the current secret and regenerate a new one.

**Comment by imdadmw** [comment]
Resolved
